### ISSUE TITLE
why cant the plants fight back

### ISSUE THREAD

**Issue by BShadid** [baronbird/gregori#1]

**Comment by baronbird** [comment]
Hi BShadid! Thanks for your concern. It is very important to me to create a fair and balanced experience for all types of organism, regardless of kingdom.

That being said, most plants are unfortunately incapable of movement, so their best bet for survival is to appear nonthreatening to other organisms and hope that they aren't harmed. There is very little I can do to change this fact.

Thanks again for following this crazy project of mine! Have a nice day, and feel free to raise any more concerns that you have.
